# Generated by Django 4.1.7 on 2023-02-23 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the farm (Ex. Fazenda São João)', max_length=255, verbose_name='Name')),
                ('geometry', models.IntegerField(help_text='Geometry of the farm (Ex. 1)', null=True, verbose_name='Geometry')),
                ('area', models.FloatField(help_text='Area of the farm (Ex. 1000)', null=True, verbose_name='Area')),
                ('centro_id', models.IntegerField(help_text='Centro ID of the farm (Ex. 1)', null=True, verbose_name='Centro ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Creation date of the farm', verbose_name='Creation Date')),
                ('last_modification_date', models.DateTimeField(auto_now=True, help_text='Last modification date of the farm', verbose_name='Last Modification Date')),
                ('is_active', models.BooleanField(default=True, help_text='Is the farm active?', verbose_name='Is Active')),
                ('municipio', models.CharField(help_text='Municipio of the farm (Ex. São Paulo)', max_length=255, verbose_name='Municipio')),
                ('estado', models.CharField(help_text='Estado of the farm (Ex. São Paulo)', max_length=255, verbose_name='Estado')),
                ('owner', models.ForeignKey(help_text='Who is the owner of the farm?', on_delete=django.db.models.deletion.CASCADE, to='farm.owner', verbose_name='Who is the owner of the farm?')),
            ],
        ),
    ]
