# Generated by Django 4.1.7 on 2023-02-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the owner (Ex. João)', max_length=255, verbose_name='Name')),
                ('document', models.CharField(help_text='Document of the owner (Ex. 12345678900)', max_length=255, verbose_name='Document')),
                ('document_type', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], default='CPF', help_text='Document type of the owner (Ex. CPF)', max_length=10, verbose_name='Document Type')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Creation date of the owner', verbose_name='Creation Date')),
                ('last_modification_date', models.DateTimeField(auto_now=True, help_text='Last modification date of the owner', verbose_name='Last Modification Date')),
                ('is_active', models.BooleanField(default=True, help_text='Is the owner active?', verbose_name='Is Active')),
            ],
        ),
    ]
