# Generated by Django 4.1.7 on 2023-03-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_farm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='area',
            field=models.FloatField(blank=True, help_text='Area of the farm (Ex. 1000)', null=True, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='centro_id',
            field=models.IntegerField(blank=True, help_text='Centro ID of the farm (Ex. 1)', null=True, verbose_name='Centro ID'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='geometry',
            field=models.IntegerField(blank=True, help_text='Geometry of the farm (Ex. 1)', null=True, verbose_name='Geometry'),
        ),
    ]
